files = ../RadialGradientSortTest/main.cpp

release:
	g++ $(files) -o radial-gradient-sort-test -lsfml-graphics -lsfml-system -lsfml-window -std=c++11
debug:
	g++ $(files) -o radial-gradient-sort-test -lsfml-graphics -lsfml-system -lsfml-window -std=c++11 -g
